#Clases, herencia y polimorfsimos

##Definiciones def

In [36]:
# Vamos a crear una definición (qué es una función integrada de Python)

def Milanesi (a,b,c):
 x = a+b*c
 return x

In [37]:
Milanesi(1,2,3)

7

In [51]:
# Vamos a crear uuna definicón que calcule la inversa de una matriz
import numpy as np

def Inv_Matrix(M):
 x= np.linalg.inv(M)
 return x



In [52]:
matrix = np.array([[3, 0, 1],
            [1, -2, 2],
            [3, 4, -1]])
matrix

array([[ 3,  0,  1],
       [ 1, -2,  2],
       [ 3,  4, -1]])

In [53]:
Inv_Matrix(matrix)

array([[ 0.75 , -0.5  , -0.25 ],
       [-0.875,  0.75 ,  0.625],
       [-1.25 ,  1.5  ,  0.75 ]])

In [54]:
import numpy as np

# Definir una matriz
matrix = np.array([[3, 0, 1],
            [1, -2, 2],
            [3, 4, -1]])

# Calcular la inversa de la matriz
inverse_matrix = np.linalg.inv(matrix)

print("Matriz original:")
print(matrix)
print("Matriz inversa:")
print(inverse_matrix)

Matriz original:
[[ 3  0  1]
 [ 1 -2  2]
 [ 3  4 -1]]
Matriz inversa:
[[ 0.75  -0.5   -0.25 ]
 [-0.875  0.75   0.625]
 [-1.25   1.5    0.75 ]]
